<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-21T21:21:44Z" name="Functional Suite" finished-at="2020-10-21T21:21:44Z" duration-ms="23">
    <groups>
    </groups>
    <test started-at="2020-10-21T21:21:44Z" name="Login Test" finished-at="2020-10-21T21:21:44Z" duration-ms="23">
      <class name="PlayAround.HollywoodBet.testing.AppTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:PlayAround.HollywoodBet.testing.AppTest@6c2a7c73]" started-at="2020-10-21T23:21:38Z" name="setup" finished-at="2020-10-21T23:21:44Z" duration-ms="5831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testTrial(java.util.Hashtable)[pri:0, instance:PlayAround.HollywoodBet.testing.AppTest@6c2a7c73]" started-at="2020-10-21T23:21:44Z" name="testTrial" data-provider="dp" finished-at="2020-10-21T23:21:44Z" duration-ms="0" status="SKIP">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
DataProvider should be static: public java.lang.Object[][] Utilities.TestUtil.getData(java.lang.reflect.Method)]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
DataProvider should be static: public java.lang.Object[][] Utilities.TestUtil.getData(java.lang.reflect.Method)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:331)
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:266)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1335)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1051)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1140)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTrial -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:PlayAround.HollywoodBet.testing.AppTest@6c2a7c73]" started-at="2020-10-21T23:21:44Z" name="teardown" finished-at="2020-10-21T23:21:44Z" duration-ms="203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- PlayAround.HollywoodBet.testing.AppTest -->
    </test> <!-- Login Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
